services:
  firstproject:
    build:
      context: .
      dockerfile:  gabi.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - db
  db:
    container_name: postgres
    image: postgres:17.0
    environment:
        POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
        POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
        PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    hostname: db
networks:
  db:
    driver: bridge

volumes:
  db:

