name: CD -frontend deploy


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/react/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        #        working-directory: ./
        working-directory: ./frontend/react
    steps:
      - uses: actions/checkout@v4
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set build no
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: build package push with maven
        run: |
          chmod +x ../../.ci/build_publish.sh
          USERNAME=gabrielagapie \
          REPO = firstproject-react \
          TAG = ${ {steps.build-number.outputs.GITHUB_OUTPUT}}\
          ../../.ci/build-publish.sh . \ 
          --build arg api_base_url = aladepeAmazon
      #      - name: change directory to root
      #        run:
      #          working-directory: ./
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: 12345
          version_description: ${{github.SHA}}
          region: ${{ secrets.REGION }}
          deployment_package:  Dockerrun.aws.json
      - name: commit and push Dockerrun.aws.json
        run: |
          git config username user.name = github-actions
          git config email user.name = github-actions@github.com
          git add ../Dockerrun.aws.json
          git commit -m "update Dockerrun.aws.json"
          git push
